//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDev_ClientTemplate.AppSubmitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppSubmitService.IAppSubmitSimulationService")]
    public interface IAppSubmitSimulationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppSubmitSimulationService/AppSubmitSimulator", ReplyAction="http://tempuri.org/IAppSubmitSimulationService/AppSubmitSimulatorResponse")]
        string AppSubmitSimulator(int processTimeMs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppSubmitSimulationService/AppSubmitSimulator", ReplyAction="http://tempuri.org/IAppSubmitSimulationService/AppSubmitSimulatorResponse")]
        System.Threading.Tasks.Task<string> AppSubmitSimulatorAsync(int processTimeMs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppSubmitSimulationServiceChannel : MasterDev_ClientTemplate.AppSubmitService.IAppSubmitSimulationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppSubmitSimulationServiceClient : System.ServiceModel.ClientBase<MasterDev_ClientTemplate.AppSubmitService.IAppSubmitSimulationService>, MasterDev_ClientTemplate.AppSubmitService.IAppSubmitSimulationService {
        
        public AppSubmitSimulationServiceClient() {
        }
        
        public AppSubmitSimulationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppSubmitSimulationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppSubmitSimulationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppSubmitSimulationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AppSubmitSimulator(int processTimeMs) {
            return base.Channel.AppSubmitSimulator(processTimeMs);
        }
        
        public System.Threading.Tasks.Task<string> AppSubmitSimulatorAsync(int processTimeMs) {
            return base.Channel.AppSubmitSimulatorAsync(processTimeMs);
        }
    }
}
